export const classNames = {
  player: "nmpv3-player",
  main: "nmpv3-main",
  miniPanel: "nmpv3-mini-panel",
  miniTitle: "nmpv3-mini-title",
  miniSubtitle: "nmpv3-mini-subtitle",
  miniMode: "nmpv3-mini-mode",
  miniActions: "nmpv3-mini-actions",
  coverButton: "nmpv3-cover-button",
  cover: "nmpv3-cover",
  coverFallback: "nmpv3-cover-fallback",
  vinylRing: "nmpv3-vinyl-ring",
  body: "nmpv3-body",
  title: "nmpv3-title",
  artist: "nmpv3-artist",
  meta: "nmpv3-meta",
  album: "nmpv3-album",
  order: "nmpv3-order",
  modeBadge: "nmpv3-mode-badge",
  lyrics: "nmpv3-lyrics",
  lyricOriginal: "nmpv3-lyric-original",
  lyricTranslation: "nmpv3-lyric-translation",
  controls: "nmpv3-controls",
  iconButton: "nmpv3-icon-button",
  previousButton: "nmpv3-previous",
  playButton: "nmpv3-play",
  nextButton: "nmpv3-next",
  bottom: "nmpv3-bottom",
  progress: "nmpv3-progress",
  time: "nmpv3-time",
  currentTime: "nmpv3-current-time",
  progressTrack: "nmpv3-progress-track",
  progressBar: "nmpv3-progress-bar",
  totalTime: "nmpv3-total-time",
  tools: "nmpv3-tools",
  volume: "nmpv3-volume",
  volumeTrack: "nmpv3-volume-track",
  volumeBar: "nmpv3-volume-bar",
  lyricsToggle: "nmpv3-lyrics-toggle",
  modeButton: "nmpv3-mode",
  playlistToggle: "nmpv3-playlist-toggle",
  minimizeButton: "nmpv3-minimize",
  playlistPanel: "nmpv3-playlist-panel",
  playlistList: "nmpv3-playlist-list",
  playlistItem: "nmpv3-playlist-item",
  playlistIndex: "nmpv3-playlist-index",
  playlistCover: "nmpv3-playlist-cover",
  playlistInfo: "nmpv3-playlist-info",
  playlistName: "nmpv3-playlist-name",
  playlistArtist: "nmpv3-playlist-artist",
  playlistDuration: "nmpv3-playlist-duration",
  status: "nmpv3-status",
  noCover: "nmpv3-no-cover",
} as const;

export const stateClassNames = {
  active: "nmpv3-active",
  dockedLeft: "nmpv3-docked-left",
  dockedRight: "nmpv3-docked-right",
  dragging: "nmpv3-dragging",
  idleFadingIn: "nmpv3-fading-in",
  idleFadingOut: "nmpv3-fading-out",
  idle: "nmpv3-idle",
  isArticle: "nmpv3-is-article",
  isMinimized: "nmpv3-is-minimized",
  isPlaying: "nmpv3-is-playing",
  playlistOpen: "nmpv3-playlist-open",
  poppingLeft: "nmpv3-popping-left",
  poppingRight: "nmpv3-popping-right",
  themeDark: "nmpv3-theme-dark",
  userPositioned: "nmpv3-user-positioned",
} as const;

export const playModeClassNames = {
  list: "nmpv3-mode-list",
  single: "nmpv3-mode-single",
  shuffle: "nmpv3-mode-shuffle",
} as const;

export function cx(...names: Array<string | false | null | undefined>): string {
  return names.filter(Boolean).join(" ");
}
